name: Towncrier Check

on: [push, pull_request]

jobs:
  towncrier-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install towncrier

      - name: Check for changelog fragments
        run: |
          if [ -z "$(ls -A changelog-fragments\*.txt)" ]; then
            echo "No changelog fragments found!";
            exit 1;
          else
            echo "Changelog fragments found:";
            ls changelog-fragments;
          fi
