name: Towncrier Check

on: [push, pull_request]

jobs:
  towncrier-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install towncrier

      - name: Check for changes compared to main and run Towncrier
        run: |
          source .venv/bin/activate
          git fetch origin main
          if ! git diff --quiet origin/main -- .; then
              echo "Changes detected, listing changelog fragments:"
              ls -la changelog-fragments/
              if towncrier check --config towncrier.toml; then
                  echo "Changelog fragments found, check passed.";
              else
                  echo "Changes detected but no changelog fragments found!";
                  exit 1;
              fi
          else
              echo "No changes in the repository.";
          fi
